### ISSUE TITLE
can I get the browser automatically refreshed when editing the swagger

### ISSUE THREAD

**Issue by xavierchow** [superbogy/zly#1]
@superbogy It does launch the browser(with https://github.com/scottie1984/swagger-ui-express/), but even if I have changed the content of the swagger file, it's not auto-refreshed, I have to refresh the webpage manually.
Is it possible to make it automatically refreshed? maybe with some helps with https://github.com/scottie1984/swagger-ui-express#custom-js.

**Comment by superbogy** [comment]
good proposal.
This feature add in current version `0.1.3`
@xavierchow

**Comment by superbogy** [comment]
done
